'use strict';
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const x = require('../causal-xenosoma.cjs');
const source = fs.readFileSync(require.resolve('../causal-xenosoma.cjs'), 'utf8');
assert.equal(source.includes('seed % 2'), false);
assert.equal(source.includes('HOLDOUT_SEEDS'), false);
const result = x.runCausalExperiment({ name: 'causal-perturbation-v1', seeds: [2, 4, 6] });
assert.equal(result.hypotheses[0].observational, result.hypotheses[1].observational);
assert.notEqual(result.hypotheses[0].counterfactual, result.hypotheses[1].counterfactual);
assert.equal(result.metrics.baselineInformationGain, 0);
assert.equal(result.metrics.baselineCannotIntervene, true);
assert.equal(result.metrics.informationGain, 1);
assert.equal(result.metrics.distinguishes, true);
assert.equal(result.metrics.rollback.applicable, false);
assert.equal(Number.isFinite(result.metrics.durationMs), true);
assert.equal(Number.isFinite(result.metrics.baselineDurationMs), true);
assert.equal(result.holdout.length, 2);
assert.equal(result.genome.calibration.grader, 'causal-xenosoma-grader-process');
assert.ok(result.trials.every(t => /^sha256:[0-9a-f]{64}$/.test(t.evidenceAnchor)));
assert.equal(new Set(result.trials.map(t => t.evidenceAnchor)).size, 3);
assert.equal(new Set(result.holdout.map(t => t.evidenceAnchor)).size, 2);
const receipt = x.persistCandidate(result, fs.mkdtempSync(path.join(os.tmpdir(), 'causal-xenosoma-')));
assert.equal(receipt.circulation.stage, 'verification');
assert.equal(receipt.circulation.authority.mutation_allowed, false);
console.log('causal xenosoma instrument: ALL PASS');
