'use strict';
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');
const x = require('../causal-xenosoma.cjs');
const source = fs.readFileSync(require.resolve('../causal-xenosoma.cjs'), 'utf8');
assert.equal(source.includes('seed % 2'), false);
assert.equal(source.includes('HOLDOUT_SEEDS'), false);
assert.equal(source.includes('even'), false);
assert.equal(source.includes('noveltyDistance: 1'), false);
const result = x.runCausalExperiment({ name: 'causal-perturbation-v4', seeds: [2, 3, 4, 5] });
assert.equal(result.hypotheses[0].observational, result.hypotheses[1].observational);
assert.notEqual(result.hypotheses[0].counterfactual, result.hypotheses[1].counterfactual);
assert.equal(result.metrics.baselineInformationGain, 0);
assert.equal(result.metrics.baselineCannotIntervene, true);
assert.equal(result.metrics.informationGain, 1);
assert.equal(result.metrics.distinguishes, true);
assert.equal(result.metrics.commitmentBeforePerturbation, true);
assert.equal(result.metrics.commitmentVerified, true);
assert.equal(result.metrics.trialClassDiversity, 2);
assert.equal(result.metrics.holdoutClassDiversity, 2);
assert.deepEqual(new Set(result.trials.map(t => t.intervention.revealedMechanism)), new Set(['alpha', 'beta']));
assert.deepEqual(new Set(result.holdout.map(t => t.intervention.output)), new Set(['alpha', 'beta']));
assert.equal(result.commitment.sequence, 1);
assert.match(result.commitment.commitmentHash, /^sha256:[0-9a-f]{64}$/);
assert.equal(result.metrics.rollback.applicable, false);
assert.equal(Number.isFinite(result.metrics.durationMs), true);
assert.equal(Number.isFinite(result.metrics.baselineDurationMs), true);
assert.equal(result.holdout.length, 2);
assert.equal(result.genome.calibration.grader, 'causal-xenosoma-grader-process');
assert.ok(result.trials.every(t => /^sha256:[0-9a-f]{64}$/.test(t.evidenceAnchor)));
assert.equal(new Set(result.trials.map(t => t.evidenceAnchor)).size, 4);
assert.equal(new Set(result.holdout.map(t => t.evidenceAnchor)).size, 2);
const postHoc = spawnSync(process.execPath, [require.resolve('../causal-xenosoma-grader.cjs'), JSON.stringify({ mode: 'reveal', seed: 2, perturbation: result.perturbation, commitmentHash: 'sha256:post-hoc' })], { encoding: 'utf8' });
assert.notEqual(postHoc.status, 0);
const committed = JSON.parse(spawnSync(process.execPath, [require.resolve('../causal-xenosoma-grader.cjs'), JSON.stringify({ mode: 'commit' })], { encoding: 'utf8' }).stdout);
assert.equal(Object.prototype.hasOwnProperty.call(committed, 'revealedMapping'), false);
const nonCircular = JSON.parse(spawnSync(process.execPath, [require.resolve('../causal-xenosoma-grader.cjs'), JSON.stringify({ mode: 'reveal', seed: 3, perturbation: { action: 'intervene', feature: 'fake', predictions: ['alpha', 'alpha'] }, commitmentHash: committed.commitmentHash })], { encoding: 'utf8' }).stdout);
assert.equal(nonCircular.output, 'beta');
assert.equal(nonCircular.commitmentHash, committed.commitmentHash);
const receipt = x.persistCandidate(result, fs.mkdtempSync(path.join(os.tmpdir(), 'causal-xenosoma-')));
assert.equal(receipt.circulation.stage, 'verification');
assert.equal(receipt.circulation.authority.mutation_allowed, false);
assert.match(receipt.commitmentRecordHash, /^sha256:[0-9a-f]{64}$/);
console.log('causal xenosoma instrument: ALL PASS');
