'use strict';
const assert = require('assert');
const fs = require('fs');
const { spawnSync } = require('child_process');
const x = require('../causal-xenosoma.cjs');

const source = fs.readFileSync(require.resolve('../causal-xenosoma.cjs'), 'utf8');
assert.equal(source.includes('commitmentBeforePerturbation: true'), false);
assert.equal(source.includes('HOLDOUT_SEEDS'), false);
assert.equal(source.includes('spawnSync'), false);

const childScript = `
  const fs = require('fs'), os = require('os'), path = require('path'), x = require(${JSON.stringify(require.resolve('../causal-xenosoma.cjs'))});
  (async () => {
    const memDir = fs.mkdtempSync(path.join(os.tmpdir(), 'causal-xenosoma-'));
    const result = await x.runCausalExperiment({ name: 'causal-perturbation-v4', seeds: [10,11,12,13], memDir, allowUnfencedTest: true });
    const crashDir = fs.mkdtempSync(path.join(os.tmpdir(), 'causal-crash-'));
    const crash = await x.commitOnly({ memDir: crashDir, allowUnfencedTest: true });
    process.stdout.write(JSON.stringify({ result, records: require(${JSON.stringify(require.resolve('../decision-loop.cjs'))}).readRecords(memDir), crash, crashRecords: require(${JSON.stringify(require.resolve('../decision-loop.cjs'))}).readRecords(crashDir) }));
  })().catch(error => { process.stderr.write(error.stack || error.message); process.exitCode = 1; });
`;
const run = spawnSync(process.execPath, ['-e', childScript], { encoding: 'utf8', timeout: 15000 });
assert.equal(run.status, 0, run.stderr || 'causal child did not complete');
const observed = JSON.parse(run.stdout);
const result = observed.result;
assert.equal(result.hypotheses[0].observational, result.hypotheses[1].observational);
assert.notEqual(result.hypotheses[0].counterfactual, result.hypotheses[1].counterfactual);
assert.equal(result.metrics.baselineInformationGain, 0);
assert.equal(result.metrics.baselineCannotIntervene, true);
assert.equal(result.metrics.informationGain, 1);
assert.equal(result.metrics.distinguishes, true);
assert.equal(result.metrics.commitmentBeforePerturbation, true);
assert.equal(result.metrics.commitmentVerified, true);
assert.equal(result.metrics.preRevealSecretAbsent, true);
assert.equal(result.metrics.nonceBits, 128);
assert.equal(result.metrics.trialClassDiversity, 2);
assert.equal(result.metrics.holdoutClassDiversity, 2);
assert.deepEqual(new Set(result.trials.map(t => t.intervention.revealedMechanism)), new Set(['alpha', 'beta']));
assert.deepEqual(new Set(result.holdout.map(t => t.intervention.output)), new Set(['alpha', 'beta']));
assert.equal(result.commitment.sequence, 1);
assert.match(result.commitment.commitmentHash, /^sha256:[0-9a-f]{64}$/);
assert.match(result.commitmentRecordHash, /^sha256:[0-9a-f]{64}$/);
assert.match(result.perturbationRecordHash, /^sha256:[0-9a-f]{64}$/);
assert.equal(observed.records.filter(record => record.kind === 'causal-xenosoma-commitment').length, 1);
assert.equal(observed.records.filter(record => record.kind === 'causal-xenosoma-perturbation').length, 1);
assert.equal(observed.records.find(record => record.kind === 'causal-xenosoma-perturbation').commitmentRecordHash, result.commitmentRecordHash);
assert.equal(observed.crashRecords.length, 1);
assert.equal(observed.crashRecords[0].recordHash, observed.crash.recordHash);
assert.equal(observed.crashRecords.some(record => record.kind === 'causal-xenosoma-perturbation'), false);
assert.equal(result.genome.calibration.grader, 'persistent-causal-xenosoma-grader');
assert.equal(new Set(result.trials.map(t => t.evidenceAnchor)).size, 4);
assert.equal(new Set(result.holdout.map(t => t.evidenceAnchor)).size, 2);
const candidate = x.persistCandidate(result, fs.mkdtempSync(require('path').join(require('os').tmpdir(), 'causal-candidate-')), null, { allowUnfencedTest: true });
assert.equal(candidate.status, 'candidate');
assert.deepEqual(candidate.unknownGates.sort(), ['rde']);
assert.equal(candidate.gates.boundary, true);
assert.equal(candidate.gates.rde, 'unknown');
assert.throws(() => x.persistCandidate(result, fs.mkdtempSync(require('path').join(require('os').tmpdir(), 'causal-production-'))), /supervisor fencing authority/);
assert.throws(() => x.persistCandidate(result, fs.mkdtempSync(require('path').join(require('os').tmpdir(), 'causal-stale-')), { root: fs.mkdtempSync(require('path').join(require('os').tmpdir(), 'causal-lease-')), token: 'stale', epoch: 7 }), /lease|fence/);
console.log('causal xenosoma commit-reveal instrument: ALL PASS');
